deployment:
  tasks:
    - export DEPLOYPATH=/home/lnq2jmdtejy1/public_html/app.bienestar-fitness.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R ./* $DEPLOYPATH
