deployment:
  tasks:
    - export DEPLOYPATH=/home/lnq2jmdtejy1/public_html/app.bienestar-fitness.com/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R /home/lnq2jmdtejy1/repositories/mi-proyecto-app/* $DEPLOYPATH



Add cPanel deploy config
